blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/pradiktabagus/split-bill/blob/main/README.md
    about: Check our comprehensive documentation before creating an issue
  - name: 💬 Discussions
    url: https://github.com/pradiktabagus/split-bill/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🚀 API Documentation
    url: https://split-bill-mu.vercel.app/api/docs
    about: View our API documentation and endpoints